# The full list of available images can be found here https://hub.docker.com/r/microsoft/devcontainers-dotnet
# noble stands for Ubuntu 24.04 LTS (Noble Numbat)
FROM mcr.microsoft.com/devcontainers/dotnet:10.0-noble
