name: Run E2E Tests on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-e2e-tests-using-docker-compose:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v7
    - name: Run E2E tests using Docker Compose
      run: |
        docker compose up --build --exit-code-from to-dos-api-dotnet-e2e-tests
