name: Run README Commands on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-getting-started-readme-commands:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v7

    - name: Run API
      uses: devcontainers/ci@v0.3
      with:
        runCmd: |
          # we need to run our Api and proceed to the next step
          # that is why we forward its output and start it in background with & at the end
          dotnet run --project ./Api --verbosity detailed > /dev/null 2>&1 &
        push: never

    - name: Run E2E Tests
      uses: devcontainers/ci@v0.3
      with:
        runCmd: |
          java -jar /karate.jar .
        push: never
